spring:
 datasource:
  url: jdbc:mysql://localhost:3306/ecommerc_gabriel
  driver-class-name: com.mysql.cj.jdbc.Driver
  username: root
  password: Gabriel@123
 jpa:
  database-platform: org.hibernate.dialect.MySQLDialect
  show-sql: true
  generate-ddl: true
  hibernate:
   ddl-auto: update
  properties:
   hibernate:
    globally_quoted_identifiers: true
    dialect: org.hibernate.dialect.MySQLDialect
    format_sql: true
    show-sql: true